#!/usr/bin/env perl

use strict;
use warnings;
use Pithub;
use Data::Dumper;
use File::Slurp qw/ slurp /;

die "Usage: gh-create-issue USER REPO TITLE\n" unless scalar @ARGV >= 3;
my ($user, $repo_name, $title) = @ARGV;

my $token     = $ENV{GITHUB_API_TOKEN};
my $api_user  = $ENV{GITHUB_USERNAME};

# Pop open a temp file in $EDITOR for the issue body.

my $tmpdir   = $ENV{TMPDIR};
my $tmpfile  = "gh-create-issue-$user-$repo_name-$$.txt";
my $tmp_path = $tmpdir . $tmpfile;

# error check result of editor call here?
my $editor      = $ENV{EDITOR};
system qq{$editor $tmp_path};
my $body = slurp $tmp_path;

my $i = Pithub::Issues->new (
							 user => $api_user,
							 token => $token
							 );

my $result = $i->create(
						user => $user,
						repo => "$repo_name",
						data => {
								 title => "$title",
								 body  => "$body",
								}
					);

while (my $row = $result->next) {
  # print in Org syntax; easy to change this
  my ($title, $number, $url, $body, $state) =
	($row->{title}, $row->{number},
	 $row->{html_url}, $row->{body},
	 $row->{state});

  $body =~ s///g;
  $state = uc $state;
  $repo_name =~ s/\./_/g;

  my $template = <<"EOF";
** $state #$number $title             			   :$repo_name:
   :PROPERTIES:
   :URL: $url
   :END:

$body
EOF

  print $template;
}
